#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    exec \
        s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 5000" \
            cd /app/changedetection s6-setuidgid abc python3 /app/changedetection/changedetection.py -d /config
else
    exec \
        s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 5000" \
            cd /app/changedetection python3 /app/changedetection/changedetection.py -d /config
fi
